### ISSUE TITLE
Rename delete.js and rename.js

### ISSUE THREAD

**Issue by KirillEmets** [AliusDieMorietur/node_cloud_server#20]
Вроде понятно, что речь про файлы, но лучше назвать deleteFile, или pmtDeleteFile.

**Comment by AliusDieMorietur** [comment]
Если переназывать то pmtDeleteFile, но тогда уже лучше всё остальное переименоать. Нарпимер: pmtRenameFile

**Comment by AliusDieMorietur** [comment]
многие функции обновили имена
